version: "3.3"
services:
  postgres:
    image: postgres
    env_file:
      - env/postgres.env

  spm:
    build: .
    env_file:
      - env/spm.env
    depends_on:
      - postgres
    ports:
      - "8081:8081"