name: Build client application

on:
  push:
    branches: ["main"]
    paths:
      - "client/**"
      - ".github/**"

jobs:
  build-and-push-client:
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/London"
      - uses: actions/checkout@v3
      - name: Setup Go 1.16
        uses: actions/setup-go@v3
        with:
          go-version: "1.16"
          check-latest: true
      - name: Build Client
        run: |
          cd client
          go build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: client/client
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
      - name: Build installer bundle
        run: |
          cd installer
          bash create_bundle.sh
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest-client"
          message: "Latest client release"
          force_push_tag: true
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: latest-client
          name: Client Latest - ${{ steps.date.outputs.date }}
          replacesArtifacts: true
          artifacts: client/client,client/installer.zip
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
